language: php

services:
  - mysql
  - postgresql

env:
  global:
    - COVERAGE=no
    - DB=mysql
    - RELEASE=stable

matrix:
  include:
    - php: 7.2
    - php: 7.2
      env: RELEASE=lowest
    - php: 7.3
      env: COVERAGE=yes
    - php: 7.3
      env: COVERAGE=yes DB=pgsql
    - php: 7.3
      env: COVERAGE=yes DB=sqlite
    - php: 7.3
      env: COVERAGE=yes DB=sqlsrv
    - php: 7.4snapshot
      env: DB=pgsql

cache:
  directories:
    - $HOME/.composer/cache
