language: php

services:
  - mysql
  - postgresql

env:
  global:
    - COVERAGE=no
    - DB=mysql
    - RELEASE=stable

matrix:
  include:
    - php: 7.2
    - php: 7.2
      env: RELEASE=lowest
    - php: 7.3
      env: COVERAGE=yes
    - php: 7.3
      env: DB=sqlite
    - php: 7.4snapshot

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - COMPOSER_FLAGS=$([ $RELEASE == "lowest" ] && echo "--prefer-lowest" || echo "")
  - PHPUNIT_FLAGS=$([ $COVERAGE == "yes" ] && echo "--coverage-clover=coverage.xml" || echo "")

install:
  - travis_retry composer update --no-interaction --no-suggest --prefer-dist --prefer-stable $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS
